services:
  - type: web
    name: emparo-peri-peri
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_DATABASE_URL
        fromDatabase:
          name: emparo-peri-peri-db
          property: connectionString
      - key: TURSO_AUTH_TOKEN
        fromDatabase:
          name: emparo-peri-peri-db
          property: authToken