services:
  - type: web
    name: emparo-peri-peri
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false