services:
  - type: web
    name: emparo-peri-peri
    env: node
    buildCommand: npm install --include=dev && cd client && npm install && npx vite build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production